services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=nyc_green_taxi
    volumes:
      - "nyc_green_taxis_volume:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"    
    networks:
      - airflow
volumes:
  nyc_green_taxis_volume:
networks:
  airflow:
    external:
      name: airflow_milestone4_default